### ISSUE TITLE
export csv has ï»¿ on the first column

### ISSUE THREAD

**Issue by ldkingvivi** [azavea/django-queryset-csv#71]
export csv has ï»¿ on the first column, looks like a pretty common issue

It only happened inside the first colomn description

**Comment by bhuber** [comment]
It's almost certainly this: https://en.wikipedia.org/wiki/Byte_order_mark .  Not sure where it's being added though.

**Comment by ldkingvivi** [comment]
Maybe the following ?

    # add BOM to suppor CSVs in MS Excel
    file_obj.write(u'\ufeff'.encode('utf8'))

**Comment by steventlamb** [comment]
Thanks @bhuber @ldkingvivi, you are both correct.

It was decided to always add this in order to support opening CSVs correctly using microsoft excel. This has been tested to work with at least *some* versions of excel. What program are you using to open your csvs? I have tested opening an export using libreoffice, emacs, and cat. None of them print the BOM.

**Comment by ldkingvivi** [comment]
Microsoft Excel for Mac 2011

**Comment by ldkingvivi** [comment]
if I remove those 2 line codes, it works great, so pretty sure that's the place

**Comment by steventlamb** [comment]
Unfortunately it looks like there's no way to export a utf-8 encoded csv that will open correctly in excel for mac as well as excel for windows.

Since the current implementation works (wth the added BOM) for Excel for Windows (the common case) as well as with other popular spreadsheet programs and text editors, it will be left as-is.

Please read this post for more information, including instructions for converting CSVs to a format ready for Excel for Mac:
http://stackoverflow.com/questions/6588068/which-encoding-opens-csv-files-correctly-with-excel-on-both-mac-and-windows
