### ISSUE TITLE
Header fields get literal fields text translation

### ISSUE THREAD

**Issue by cubiczx** [azavea/django-queryset-csv#73]
I want you to take title and get Título

Anexo.csv:
```csv
ID,Título,fichero,orden
1,Maniobras de reanimación. Soporte vital básico con y sin desfibrilador,anexos/a1.pdf,0
```

views.py:
```python
class Anexo(models.Model):
    # Anexo Fields
    title = models.CharField(_(u'Título'), max_length=255)
    fichero = models.FileField(upload_to="anexos")
    orden = models.PositiveSmallIntegerField(default=0, blank=False, null=False)

    def __unicode__(self):
        return strip_tags(self.title)
```

**Comment by cubiczx** [comment]
I get your library djqscsv.py and change in function write_csv:
```python
dict((field.name, field.verbose_name.encode('utf-8'))
````
for:
```python
dict((field.name, field.name.encode('utf-8'))
```

**Comment by steventlamb** [comment]
I'm not sure what you're asking. The default behavior here would be to return `ID,Título,fichero,orden` for this model. This is because the keyword argument `use_verbose_names` defaults to `True`.

If you do not want this behavior, please call `render_to_csv_response` or `write_csv` with it set to false:
```render_to_csv_response(queryset, use_verbose_names=False)```

Please review README section on keyword arguments for more information about customizing behavior:
https://github.com/azavea/django-queryset-csv#keyword-arguments

**Comment by cubiczx** [comment]
Thanks. When I try I confirm.

**Comment by cubiczx** [comment]
I solve in models return using:
```python
return strip_tags(self.field)
```
