### ISSUE TITLE
Cleaning filenames provided by the keyword

### ISSUE THREAD

**Issue by audiolion** [azavea/django-queryset-csv#92]
I pass in the name of an `event` object to the `filename` keyword in `render_to_csv_response()`. If the `title` attribute of the `event` contains a `.` then I get the error that the file extension must be `.csv`.

I can just do a `event.title.replace('.', '')` before passing it in, but I am wondering why not include this line in the `_validate_and_clean_filename()` function to sanitize the input?

I can submit a PR for it if you are ok with the idea

**Comment by maurizi** [comment]
I see the problem, unfortunately, I don't know if there is a good solution.

The gist of the problem is that this library always outputs filenames with a `.csv` extension - if given a filename with a `.csv` extension it uses it directly, if given a filename without a `.csv` extension it adds one, and if given a filename with a different extension it throws the validation error you've encountered.

However, there isn't an easy way to distinguish between case two (no extension) and case three (wrong extension) when the part of the filename before the extension has a `.` character in it.

This is relatively easy to remedy on the caller's end though - just pass in a filename with `.csv` in it already and it can contain as many spaces as you want!

For your use case, I think the following would work:
```python
return render__to_csv_response(qs, filename=event.title + '.csv')
```

**Comment by audiolion** [comment]
Hey sorry forgot to comment back here, I had forked the project to implement the functionality I wanted and as I was going through the source code I found the 'filename' kwarg, not sure if I missed it in the documentation all this time but I never knew that you could supply one, once I realized that I just went the route you proposed. Thanks
